accordion-padding = 30
after-login-command = []
after-startup-command = ["exec-and-forget sketchybar", "exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0"]
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
exec-on-workspace-change = ["/bin/bash", "-c", "sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE"]
on-focus-changed = []
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
start-at-login = false

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}"

[gaps.inner]
horizontal = 10
vertical = 10

[gaps.outer]
bottom = 10
left = 10
right = 10
top = 40

[key-mapping]
preset = "qwerty"

[mode.join.binding]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]
esc = "mode main"

[mode.main.binding]
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
alt-a = "workspace A"
alt-b = "workspace B"
alt-c = "workspace C"
alt-comma = "layout accordion horizontal vertical"
alt-e = "workspace E"
alt-f = "workspace F"
alt-g = "workspace G"
alt-h = "focus left"
alt-i = "workspace I"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-m = "workspace M"
alt-minus = "macos-native-minimize"
alt-n = "workspace N"
alt-o = "workspace O"
alt-p = "workspace P"
alt-q = "workspace Q"
alt-r = "workspace R"
alt-s = "workspace S"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"
alt-shift-a = "move-node-to-workspace A"
alt-shift-b = "move-node-to-workspace B"
alt-shift-c = "move-node-to-workspace C"
alt-shift-d = "move-node-to-workspace D"
alt-shift-e = "move-node-to-workspace E"
alt-shift-equal = "resize smart +50"
alt-shift-f = "move-node-to-workspace F"
alt-shift-g = "move-node-to-workspace G"
alt-shift-h = "move left"
alt-shift-i = "move-node-to-workspace I"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-m = "move-node-to-workspace M"
alt-shift-minus = "resize smart -50"
alt-shift-n = "move-node-to-workspace N"
alt-shift-o = "move-node-to-workspace O"
alt-shift-p = "move-node-to-workspace P"
alt-shift-q = "move-node-to-workspace Q"
alt-shift-r = "move-node-to-workspace R"
alt-shift-s = "move-node-to-workspace S"
alt-shift-semicolon = "mode service"
alt-shift-slash = "mode join"
alt-shift-t = "move-node-to-workspace T"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-shift-u = "move-node-to-workspace U"
alt-shift-v = "move-node-to-workspace V"
alt-shift-w = "move-node-to-workspace W"
alt-shift-x = "move-node-to-workspace X"
alt-shift-y = "move-node-to-workspace Y"
alt-shift-z = "move-node-to-workspace Z"
alt-slash = "layout tiles horizontal vertical"
alt-space = "fullscreen"
alt-t = "workspace T"
alt-tab = "workspace-back-and-forth"
alt-u = "workspace U"
alt-v = "workspace V"
alt-w = "workspace W"
alt-x = "workspace X"
alt-y = "workspace Y"
alt-z = "workspace Z"

[mode.service.binding]
backspace = ["close-all-windows-but-current", "mode main"]
esc = ["reload-config", "mode main"]
f = ["layout floating tiling", "mode main"]
r = ["flatten-workspace-tree", "mode main"]

[[on-window-detected]]
run = "move-node-to-workspace T"

[on-window-detected.if]
app-id = "com.github.wez.wezterm"

[[on-window-detected]]
run = "move-node-to-workspace T"

[on-window-detected.if]
app-id = "org.alacritty"

[[on-window-detected]]
run = "move-node-to-workspace T"

[on-window-detected.if]
app-id = "net.kovidgoyal.kitty"

[[on-window-detected]]
run = "move-node-to-workspace B"

[on-window-detected.if]
app-id = "org.mozilla.firefox"

[[on-window-detected]]
run = "move-node-to-workspace B"

[on-window-detected.if]
app-id = "org.mozilla.firefoxdeveloperedition"

[[on-window-detected]]
run = "move-node-to-workspace B"

[on-window-detected.if]
app-id = "com.google.Chrome"

[[on-window-detected]]
run = "move-node-to-workspace B"

[on-window-detected.if]
app-id = "com.apple.Safari"

[[on-window-detected]]
run = "move-node-to-workspace B"

[on-window-detected.if]
app-id = "company.thebrowser.Browser"

[[on-window-detected]]
run = "move-node-to-workspace B"

[on-window-detected.if]
app-id = "com.nicesoftware.dcvviewer"

[[on-window-detected]]
run = "move-node-to-workspace F"

[on-window-detected.if]
app-id = "com.apple.finder"

[[on-window-detected]]
run = "move-node-to-workspace I"

[on-window-detected.if]
app-id = "com.jetbrains.intellij"

[[on-window-detected]]
run = "move-node-to-workspace I"

[on-window-detected.if]
app-id = "com.microsoft.VSCode"

[[on-window-detected]]
run = "move-node-to-workspace M"

[on-window-detected.if]
app-id = "com.tinyspeck.slackmacgap"

[[on-window-detected]]
run = "move-node-to-workspace M"

[on-window-detected.if]
app-id = "com.microsoft.Outlook"

[[on-window-detected]]
run = "move-node-to-workspace M"

[on-window-detected.if]
app-id = "com.amazon.Amazon-Chime"

[[on-window-detected]]
run = "move-node-to-workspace N"

[on-window-detected.if]
app-id = "md.obsidian"
